[phases.setup]
nixPkgs = ["python313", "nodejs_20", "postgresql", "gcc"]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    ". /app/.venv/bin/activate && pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    ". /app/.venv/bin/activate && python manage.py migrate"
]

[start]
cmd = ". /app/.venv/bin/activate && python manage.py collectstatic --noinput && gunicorn warehouse.wsgi --log-file -"
