[phases.setup]
nixPkgs = ["python313", "nodejs_20", "postgresql"]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    ". /app/.venv/bin/activate && pip install -r requirements.txt",
    "npm install --prefix frontend"
]

[phases.build]
cmds = [
    "npm run build --prefix frontend",
    ". /app/.venv/bin/activate && python manage.py collectstatic --noinput",
    ". /app/.venv/bin/activate && python manage.py migrate"
]

[start]
cmd = ". /app/.venv/bin/activate && gunicorn warehouse.wsgi --log-file -"
