[phases.setup]
nixPkgs = ["python3", "nodejs", "postgresql", "gcc"]

[phases.install]
cmds = [
    "python3 -m venv /app/.venv",
    ". /app/.venv/bin/activate && pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    ". /app/.venv/bin/activate && python3 manage.py collectstatic --noinput"
]

[start]
cmd = ". /app/.venv/bin/activate && python3 manage.py migrate && gunicorn warehouse.wsgi --log-file -"
